version: 0.1.{build}

skip_tags: true

environment:
    matrix:
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python35-x64"

init:
    - echo %PYTHON%
    - set PATH=%PYTHON%\;%PYTHON%\Scripts\;%PATH%

install:
    - pip install -r .\requirements.txt
    - pip install coverage

test_script:
    - python --version
    - coverage run .\test.py -v
    - coverage report

build: off
