language: python
python:
    - 2.7
    - 3.5
    - nightly
    - pypy3

sudo: false

install:
    - pip install -r ./requirements.txt
    - pip install coveralls

script:
    - python --version
    - coverage run ./test.py -v
    - coverage report

after_success:
    - coveralls
